[project]
name = "linear-project-updates"
version = "0.3.0"
description = "Fetch Linear project updates via GraphQL API"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
]

[project.scripts]
linear-updates = "linear_updates:main"
